version: '2'
services:
    config:
        container_name: "config-primary-$RELEASE"
        build:
            context: .
            dockerfile: Dockerfile.config
        image: config:latest
        ports:
             - 8081:8081
        networks:
            - spring-cloud-network
        links:
            - discovery:discovery
            - gateway:gateway
            - csa:csa
            - backend-server:backend-server
            - ariba-server:ariba-server
        volumes:
            - spring-cloud-config-repo:/var/lib/spring-cloud/config-repo
        logging:
            driver: json-file
    discovery:
        container_name: "discovery-primary-$RELEASE"
        build:
            context: .
            dockerfile: Dockerfile.discovery
        image: discovery:latest
        ports:
            - 8082:8082
        networks:
            - spring-cloud-network
        links:
            - config:config
            - gateway:gateway
            - csa:csa
            - backend-server:backend-server
            - ariba-server:ariba-server
            - auth-server
            - bootadmin-server:bootadmin-server
        depends_on:
            - config
        logging:
            driver: json-file
    auth-server:
        container_name: "auth-server-primary-$RELEASE"
        build:
            context: .
            dockerfile: Dockerfile.auth
        image: auth-server:latest
        ports:
            - 9101:9101
        networks:
            - spring-cloud-network
        links:
            - discovery:discovery
            - config:config
            - bootadmin-server
        depends_on:
            - discovery
        logging:
            driver: json-file
    gateway:
        container_name: "gateway-primary-$RELEASE"
        build:
            context: .
            dockerfile: Dockerfile.gateway
        image: gateway:latest
        ports:
            - 8080:8080
        networks:
            - spring-cloud-network
        links:
            - discovery:discovery
            - config:config
            - csa:csa
            - backend-server:backend-server
            - ariba-server:ariba-server
            - auth-server
        depends_on:
            - auth-server
        logging:
            driver: json-file
    csa:
        container_name: "csa-primary-$RELEASE"
        build:
            context: .
            dockerfile: Dockerfile.csa
        image: csa:latest
        restart: always
        ports:
            - 8085:8085
        networks:
            - spring-cloud-network
        links:
            - discovery:discovery
            - config:config
            - gateway:gateway
        depends_on:
            - gateway
        logging:
            driver: json-file
    backend-server:
        container_name: "backend-primary-$RELEASE"
        build:
            context: .
            dockerfile: Dockerfile.backend
        image: backend:latest
        restart: always
        ports:
            - 8087:8087
        networks:
            - spring-cloud-network
        links:
            - discovery:discovery
            - config:config
            - gateway:gateway
        depends_on:
            - gateway
        logging:
            driver: json-file
    ariba-server:
        container_name: "ariba-primary-$RELEASE"
        build:
            context: .
            dockerfile: Dockerfile.ariba
        image: ariba:latest
        restart: always
        ports:
            - 8086:8086
        networks:
            - spring-cloud-network
        links:
            - discovery:discovery
            - config:config
            - gateway:gateway
        depends_on:
            - gateway
        logging:
            driver: json-file
     bootadmin-server:
        container_name: "bootadmin-server-primary-$RELEASE"
        build:
            context: .
            dockerfile: Dockerfile.bootadmin
        image: bootadmin-server:latest
        ports:
             - 9142:9142
        links:
             - discovery:discovery
             - gateway:gateway
        networks:
            - spring-monitor-network
        restart: always
        volumes:
            - spring-cloud-config-repo:/var/lib/spring-cloud/config-repo
        logging:
            driver: json-file

networks:
    spring-cloud-network:
        driver: bridge
volumes:
    spring-cloud-config-repo:
        external: true