version: '2'
services:
    config-server:
        container_name: "config-server-primary-$RELEASE"
        build:
            context: .
            dockerfile: Dockerfile.config
        image: sbandyo2/config-server:latest
        ports:
             - 8081:8081
        networks:
            - spring-cloud-network
        volumes:
            - spring-cloud-config-repo:/var/lib/spring-cloud/config-repo
        logging:
            driver: json-file
    discovery:
        container_name: "discovery-primary-$RELEASE"
        build:
            context: .
            dockerfile: Dockerfile.discovery
        image: discovery:latest
        ports:
            - 8082:8082
        networks:
            - spring-cloud-network
        links:
            - config-server:config-server
        depends_on:
            - config-server
        logging:
            driver: json-file
    auth-server:
        container_name: "auth-server-primary-$RELEASE"
        build:
            context: .
            dockerfile: Dockerfile.auth
        image: auth-server:latest
        ports:
            - 9101:9101
        networks:
            - spring-cloud-network
        links:
            - discovery:discovery
            - config-server:config-server
        depends_on:
            - discovery
        logging:
            driver: json-file
    gateway:
        container_name: "gateway-primary-$RELEASE"
        build:
            context: .
            dockerfile: Dockerfile.gateway
        image: gateway:latest
        ports:
            - 8080:8080
        networks:
            - spring-cloud-network
        links:
            - discovery:discovery
            - config-server:config-server
        depends_on:
            - auth-server
        logging:
            driver: json-file
    csa:
        container_name: "csa-primary-$RELEASE"
        build:
            context: .
            dockerfile: Dockerfile.csa
        image: csa:latest
        restart: always
        ports:
            - 8085:8085
        networks:
            - spring-cloud-network
        links:
            - discovery:discovery
            - config-server:config-server
            - gateway
        depends_on:
            - gateway
        logging:
            driver: json-file
    backend-server:
        container_name: "backend-primary-$RELEASE"
        build:
            context: .
            dockerfile: Dockerfile.backend
        image: backend:latest
        restart: always
        ports:
            - 8087:8087
        networks:
            - spring-cloud-network
        links:
            - discovery:discovery
            - config-server:config-server
            - gateway
        depends_on:
            - gateway
        logging:
            driver: json-file
    ariba-server:
        container_name: "ariba-primary-$RELEASE"
        build:
            context: .
            dockerfile: Dockerfile.ariba
        image: ariba:latest
        restart: always
        ports:
            - 8086:8086
        networks:
            - spring-cloud-network
        links:
            - discovery:discovery
            - config-server:config-server
            - gateway
        depends_on:
            - gateway
        logging:
            driver: json-file

networks:
    spring-cloud-network:
        driver: bridge
volumes:
    spring-cloud-config-repo:
        external: true